# Generated by Django 4.2.4 on 2023-10-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_quests',
            new_name='no_of_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
    ]
